### ISSUE TITLE
NetworkTables crashed

### ISSUE THREAD

**Issue by Megamind101** [robotpy/pynetworktables#10]
```
Exception in thread Server Connection Reader Thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/site-packages/networktables2/connection.py", line 188, in run
    self.connection.read(self.adapter)
  File "/usr/local/lib/python3.4/site-packages/networktables2/connection.py", line 141, in read
    adapter.clientHello(protocolRevision)
  File "/usr/local/lib/python3.4/site-packages/networktables2/server.py", line 113, in clientHello
    self.entryStore.sendServerHello(self.connection)
  File "/usr/local/lib/python3.4/site-packages/networktables2/server.py", line 199, in sendServerHello
    connection.sendEntryAssignment(entry)
  File "/usr/local/lib/python3.4/site-packages/networktables2/connection.py", line 126, in sendEntryAssignment
    entry.getId(), entry.getSequenceNumber())
  File "/usr/local/lib/python3.4/site-packages/networktables2/connection.py", line 47, in send
    wstream.write(self.STRUCT.pack(*args))
struct.error: 'H' format requires 0 <= number <= 65535
```

**Comment by virtuald** [comment]
Note to self: This happened when disconnecting / reconnecting the SmartDashboard
