### ISSUE TITLE
'ClientNetworkTableEntryStore' object has no attribute 'mutex'

### ISSUE THREAD

**Issue by computer-whisperer** [robotpy/pynetworktables#15]
```
ERROR:nt:Exception in valueChanged callback!
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/networktables2/networktablenode.py", line 159, in fireTableListeners
    listener.valueChanged(None, key, value, isNew)
  File "/usr/lib/python3.4/site-packages/networktables/__init__.py", line 86, in valueChanged
    value, isNew)
  File "/home/christian/PycharmProjects/RoboRIO-webdash/webdash/networktables_controller.py", line 50, in val_listener
    target_ref[key] = source.getValue(key)
  File "/usr/lib/python3.4/site-packages/networktables/__init__.py", line 619, in getValue
    return self.node.getValue(self.absoluteKeyCache.get(key))
  File "/usr/lib/python3.4/site-packages/networktables2/networktablenode.py", line 107, in getValue
    with self.entryStore.mutex:
AttributeError: 'ClientNetworkTableEntryStore' object has no attribute 'mutex'
```

It seems that neither ```ClientNetworkTableEntryStore``` object, nor any parent classes, ever initialize a ```mutex``` object. The ```AbstractNetworkTableEntryStore``` object does initialize an ```entry_lock``` object, but i'm not sure if that is supposed to be for a different function.

**Comment by virtuald** [comment]
Oops, was supposed to be entry_lock.
