### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by CarterFendley** [robotpy/pynetworktables#17]
```
14:27:49:888 INFO    : wpilib              : WPILib version 2015.0.10
14:27:49:888 INFO    : wpilib              : HAL base version 2015.0.10; sim platform version 2015.0.10
Team 1418's 2015 Code
14:27:50:283 INFO    : nt                  : Server 0x1039d1da0 entered connection state: GOT_CONNECTION_FROM_CLIENT
14:27:50:284 INFO    : nt                  : Server 0x1039d1da0 entered connection state: CONNECTED_TO_CLIENT
14:27:51:335 INFO    : autonomous          : Begin initializing autonomous mode switcher
14:27:51:349 INFO    : autonomous          : Loaded autonomous modes:
14:27:51:349 INFO    : autonomous          :  -> Drive Forward [Default]
14:27:51:350 INFO    : autonomous          : Autonomous switcher initialized
14:27:51:351 INFO    : robot               : Entering disabled mode
Exception in thread Write Manager Thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/networktables2/common.py", line 249, in run
    transactions.append(entry.getUpdateBytes())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/networktables2/entry.py", line 88, in getUpdateBytes
    self.type.writeBytes(b, self.value)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/networktables2/type.py", line 63, in writeBytes
    s = value.encode('utf-8')
AttributeError: 'float' object has no attribute 'encode'
```

**Comment by virtuald** [comment]
What was happening is that the entry was sent by the client to the server, and it was of a different type than what the server had sent. There's a better error message in place now.
